name: macOS Build

on: [push]

env:
  build-dir: build
  build-type: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.15, macos-11.0]

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/cmake
      with:
        source-dir: '${{github.workspace}}'
        build-dir: '${{github.workspace}}/${{env.build-dir}}'
        build-type: '${{env.build-type}}'

    - uses: actions/upload-artifact@v2
      with:
        name: VST3_Project_Generator.app
        path: '${{github.workspace}}/${{env.build-dir}}/${{env.build-type}}/VST3_Project_Generator.app'
