name: Windows build

on: [push]

env:
  build-dir: build
  build-type: Debug

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019]

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/cmake
      with:
        source-dir: '${{github.workspace}}'
        build-dir: '${{github.workspace}}/${{env.build-dir}}'
        build-type: '${{env.build-type}}'

    - uses: actions/upload-artifact@v2
      with:
        name: VST3_Project_Generator
        path: '${{github.workspace}}/${{env.build-dir}}/${{env.build-type}/VST3_Project_Generator'
 