name: Windows build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019]

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/cmake
      with:
        source-dir: '${{github.workspace}}'
        build-dir: '${{github.workspace}}/build'
        build-type: 'Debug'

    - uses: actions/upload-artifact@v2
      with:
        name: win32-project_generator
        path: '${{github.workspace}}/build/Debug/VST3_Project_Generator'
 